[package]
name = "p2pass"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
base64 = "0.22.1"
rand = "0.8.5"
rust-crypto = "0.2.36"
sha256 = "1.5.0"
sodiumoxide = "0.2.7"
